compile: Remove -Werror and avoid build failures because of warnings
Using -Werror on production is a bad idea, as otherwise harmless warnings
get treated as errors breaking builds. This is currently the case with
Nios-II architecture toolchain, warning about a deprecated macro:

../usr/nios2-buildroot-linux-gnu/sysroot/usr/include/features.h:148:3:
error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"

Instead of trying to fix the macro, let's fix the real issue here,
and remove -Werror.

Signed-off-by: Ezequiel Garcia <ezequiel@vanguardiasur.com.ar>