event.c: Cast pthread_t to unsigned long instead of unsigned int
On 64bit machines it ends up in errors

event.c:85:67: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  a_event->tid_hex_str_len = sprintf(a_event->tid_hex_str, "0x%x", (unsigned int)a_event->tid);

Signed-off-by: Khem Raj <raj.khem@gmail.com>